name: 'Test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install && npx hass-taste-test

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            **/__diff_output__/**/
