name: 'Test'

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install && npx hass-taste-test

      - name: Build
        run: npm run build

      - name: Test Firefox
        run: BROWSER=firefox npm run test

      - name: Test Chromium
        run: BROWSER=chromium npm run test

      - name: Test Webkit
        run: |
          sudo apt-get install libegl1 libopus0 libwoff1 libharfbuzz-icu0 gstreamer1.0-plugins-base libgstreamer-gl1.0-0 gstreamer1.0-plugins-bad libopenjp2-7 libwebpdemux2 libenchant1c2a libhyphen0 libgles2 gstreamer1.0-libav
          BROWSER=webkit npm run test

      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            **/__diff_output__/**/
